export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const CREATE_ADMIN = 'CREATE_ADMIN';

export const COMPLAINT_CREATE = 'COMPLAINT_CREATE';
export const COMPLAINT_UPDATE = 'COMPLAINT_UPDATE';
export const COMPLAINTS_FETCH_BY_USER_ID = 'COMPLAINTS_FETCH_BY_USER_ID';
export const COMPLAINTS_FETCH = 'COMPLAINTS_FETCH';
